//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hamburg.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HamburgEntities : DbContext
    {
        public HamburgEntities()
            : base("name=HamburgEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AboutOne> AboutOnes { get; set; }
        public virtual DbSet<AboutTitle> AboutTitles { get; set; }
        public virtual DbSet<AboutTwo> AboutTwoes { get; set; }
        public virtual DbSet<AdminAccount> AdminAccounts { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Gallery> Galleries { get; set; }
        public virtual DbSet<HomeCountry> HomeCountries { get; set; }
        public virtual DbSet<HomeEducation> HomeEducations { get; set; }
        public virtual DbSet<HomeTitle> HomeTitles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
